services:
  ip-bot:
    build: .
    network_mode: host  
    environment:
      - TOKEN=${TOKEN}
      - SEND_CHANNEL=${SEND_CHANNEL}
      - CLIENT_ID=${CLIENT_ID}
      - GUILD_ID=${GUILD_ID}
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules # Ensure node_modules is not overwritten
    restart: always
